# Generated by Django 2.2.6 on 2019-10-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crashdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_id', models.TextField(blank=True, db_column='Crash ID', null=True)),
                ('adjusted_average_daily_traffic_amount', models.TextField(blank=True, db_column='Adjusted Average Daily Traffic Amount', null=True)),
                ('commercial_motor_vehicle_flag', models.TextField(blank=True, db_column='Commercial Motor Vehicle Flag', null=True)),
                ('crash_death_count', models.TextField(blank=True, db_column='Crash Death Count', null=True)),
                ('crash_time', models.TextField(blank=True, db_column='Crash Time', null=True)),
                ('crash_total_injury_count', models.TextField(blank=True, db_column='Crash Total Injury Count', null=True)),
                ('curve_degrees', models.TextField(blank=True, db_column='Curve Degrees', null=True)),
                ('curve_type', models.TextField(blank=True, db_column='Curve Type', null=True)),
                ('day_of_week', models.TextField(blank=True, db_column='Day of Week', null=True)),
                ('inside_shoulder_width_on_divided_highway', models.TextField(blank=True, db_column='Inside Shoulder Width on Divided Highway', null=True)),
                ('latitude', models.TextField(blank=True, db_column='Latitude', null=True)),
                ('light_condition', models.TextField(blank=True, db_column='Light Condition', null=True)),
                ('longitude', models.TextField(blank=True, db_column='Longitude', null=True)),
                ('manner_of_collision', models.TextField(blank=True, db_column='Manner of Collision', null=True)),
                ('number_of_lanes', models.TextField(blank=True, db_column='Number of Lanes', null=True)),
                ('object_struck', models.TextField(blank=True, db_column='Object Struck', null=True)),
                ('outside_shoulder_width_on_divided_highway', models.TextField(blank=True, db_column='Outside Shoulder Width on Divided Highway', null=True)),
                ('property_damages', models.TextField(blank=True, db_column='Property Damages', null=True)),
                ('road_class', models.TextField(blank=True, db_column='Road Class', null=True)),
                ('street_name', models.TextField(blank=True, db_column='Street Name', null=True)),
                ('street_number', models.TextField(blank=True, db_column='Street Number', null=True)),
                ('surface_condition', models.TextField(blank=True, db_column='Surface Condition', null=True)),
                ('weather_condition', models.TextField(blank=True, db_column='Weather Condition', null=True)),
                ('driver_alcohol_result', models.TextField(blank=True, db_column='Driver Alcohol Result', null=True)),
            ],
            options={
                'db_table': 'CrashData',
                'managed': False,
            },
        ),
    ]
